[44기 김영운] ADD: 로그인 회원가입 레이아웃 및 기능 구현
wecode-bootcamp-korea/44-1st-four-branch-frontend pull request #10
Opened 2023-04-07 10:49 UTC by KIMYOUNGWOON

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 성, 이름, 이메일, 비밀번호, 체크박스 체크시 회원가입 기능 구현
- 이메일, 비밀번호 입력창을 사용한 로그인 기능 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 로그인 / 회원가입 레이아웃
- 로그인 / 회원가입이 페이지 형식이 아니라 모달 팝업창으로 뜨는 방식이며 로그인창과 회원가입창이 공통된 부분 외에 몇가지 요소만 달라서 컴포넌트 재사용을 통해 컴포넌트 하나로 두가지 창을 구현했습니다.

2023-04-10 02:20 UTC, we-dohyeon requested changes
수고하셨습니다 영운님! 리뷰 반영해주세요~

2023-04-10 02:20 UTC, we-dohyeon commented on src/Components/CheckUser/CheckUser.js
> +  }
LOGIN_DATA 와 SIGNUP_DATA 객체의 title, button 에 할당된 값이 각각 '로그인', '회원가입' 으로 동일합니다.
setModalMode('로그인') 처럼 활용하는 것은 어떨까요? 하나의 문자열로도 충분히 활용할 수 있을 것 같습니다.

2023-04-10 02:20 UTC, we-dohyeon commented on src/Components/UserModal/UserModal.js
> +  const [isCheckingBox, setIsCheckingBox] = useState('');
비슷한 성격의 state들을 하나의 값으로 관리해보세요!
ex) useState({firstName : '', lastName: ''})

2023-04-10 02:20 UTC, we-dohyeon commented on src/Components/UserModal/UserModal.js
> +        fetch('http://10.58.52.78:3000/users/signin', {
여러번 동일한 조건이 반복되고 있습니다! 해당 부분을 새로운 변수로 만들면서 가독성을 높여보세요!

2023-04-10 02:20 UTC, we-dohyeon commented on src/Components/UserModal/UserModal.js
> +          }),
```suggestion
          body: JSON.stringify({
            firstName,
            LastName: lastName,
            email: emailValue,
            password: passwordValue,
          }),
```
객체의 key, value가 동일할 때는 이렇게 단축속성명을 적용할 수도 있습니다!

2023-04-10 02:20 UTC, we-dohyeon commented on src/Components/UserModal/UserModal.js
> +          }),
그렇다고 key, value를 꼭 맞출 필요는 없으니 참고해주세요!

2023-04-10 02:20 UTC, we-dohyeon commented on src/Components/UserModal/UserModal.js
> +            회원가입을 통해 주문 내역을 확인하고 지난 구매 상품을 재구매하실 수
로그인과 회원가입을 아예 분리하는 것은 어떨까요?
cosnt LoginComponent = <div></div>;
cosnt SignupComponent = <div></div>;

return ({title === "로그인" ? <LoginComponent /> : <SignupComponent />})

2023-04-10 07:11 UTC, KIMYOUNGWOON commented on src/Components/UserModal/UserModal.js
> +            회원가입을 통해 주문 내역을 확인하고 지난 구매 상품을 재구매하실 수
수정사항 반영했습니다.

2023-04-10 08:26 UTC, we-dohyeon reviewed
리뷰 1건과 충돌 해결해주세요!

2023-04-10 08:26 UTC, we-dohyeon commented on src/Components/UserModal/UserModal.js
> +      if (!(emailCheck && passwordCheck && isChecked)) {
const test = emailCheck && passwordCheck && isChecked;
이렇게 활용해보세요!

2023-04-11 03:04 UTC, we-dohyeon commented
LGTM 👍

2023-04-11 03:04 UTC, merged